optimism.tokenlist.json
We were using the `Synthetix` address on Optimistic Ethereum and Optimistic Kovan, whereas we should use their `ProxyERC20` address on both networks. This PR updates to those addresses. For reference: 
https://github.com/Synthetixio/synthetix/blob/bf80204617abbf0a8893363762d5bcab5692ca0f/publish/deployed/mainnet-ovm/versions.json
and
https://github.com/Synthetixio/synthetix/blob/bf80204617abbf0a8893363762d5bcab5692ca0f/publish/deployed/kovan-ovm/versions.json
=> Update L2 SNX addresses

optimism.tokenlist.json
I think this is causing missing tokens on Uniswap app.
=> add missing 0x to RGT to be in line with pattern (and hopefully fix Uniswap app)

src/validate.ts
Add special condition for the DF token to the validation script as that is not fully erc20 compliant as it has the symbol and name properties as bytes32 types rather than strings.
Exclude the DCN token from validation as well because its symbol on chain and in the token list intentionally differ, i.e. `٨` vs `DCN`
Exclude USX from bridge validation as this is using a custom bridge.
We also fix an issue with the validation script which was silently failing on the bridge address validation, [see a failing bridge address validation here](https://github.com/ethereum-optimism/ethereum-optimism.github.io/runs/4650694044?check_suite_focus=true) which as still passing in CI. 
[Here is a correctly failing CI](https://github.com/ethereum-optimism/ethereum-optimism.github.io/runs/4651 …
=> Token and bridge validation updates and fixes

optimism.tokenlist.json
The name of Optimism's token is OP right now. This PR will fix it to be OP
=> Fixing OP token name

.github/workflows/validate.yml
Gives validate.yml the correct permissions to comment on PRs when PRs
are made by external contributors.
=> feat(ci): correct validate.yml perms

.github/workflows/validate.yml
Updates CI so PR comments properly work for forks. Requires that we use
pull_request_target with some hacky code. Please review carefully and
think of potential ways in which the external clone could be exploited.
=> fix(ci): make PR comments work for forks

.github/workflows/validate.yml
One last CI fix, always pass the --tokens parameter by quoting.
=> fix(ci): always pass tokens parameter

data/wstETH/data.json
Add Ethereum/Optimism mainnet config for wstETH token.
**Tests**
According to the instruction, tests are not required.
* Token bridged via custom bridge implementation: https://github.com/lidofinance/lido-l2/tree/main/contracts/optimism (just like for the Kovan network).
* To bridge tokens using the `CrossChainMessenger` class from the [@eth-optimism/sdk](https://github.com/ethereum-optimism/optimism/tree/develop/packages/sdk) package, use the `DAIBridgeAdapter`. `StandardBridgeAdapter` will throw the error: "token pair not supported by bridge" on the `supportsTokenPair` method call (just like for the Kovan network).
=> Add mainnet config for wstETH token

data/USDT/data.json
Adding Goerli USDT addresses
L1 https://goerli.etherscan.io/token/0xc2c527c0cacf457746bd31b2a698fe89de2b6d49 there isn't an official USDT testnet token, so I picked this one that has SOME uniswap liquidity and the most holders
L2 https://goerli-optimism.etherscan.io/address/0x853eb4ba5d0ba2b77a0a5329fd2110d5ce149ece (just deployed this) 
**Tests**
**Metadata**
- Fixes https://linear.app/optimism/issue/ENG-2542/redeploy-standard-tokens-update-tokenlist
=> Add Goerli USDT

.github/workflows/validate.yml
Has CI record PR numbers in artifacts. For whatever reason, GitHub does not make it easy to figure out which PR triggered a given workflow. Recording the PR number as an artifact is an easy hack that makes it possible for external bots to access this information.
=> fix(ci): have CI record PR numbers

data/FLASH/data.json, data/FLASH/logo.svg
Adding the bridge information for the Flashstake token. The Flashstake token deployed on Optimism was performed using the L2StandardTokenFactory contract.
Deployment details: https://optimistic.etherscan.io/tx/0xb4682fed21ac89736d8f1b4b47bd0e4923d04b8d91e6f757477cb93baaa776b5
**Tests**
We have deployed the Optimism token as mentioned above. There were two test transactions made to ensure funds were bridged successfully. Details: https://optimistic.etherscan.io/token/0x86bea60374f220de9769b2fef2db725bc1cdd335
N/A
**Metadata**
N/A
=> feat: add Flashstake bridge info

optimism.tokenlist.json, package.json, src/schemas.ts, yarn.lock
- Switch ts-node to tsx because tsx is more forgiving and less likely to break [(see chart below)](https://github.com/privatenumber/ts-runtime-comparison)
- it's also faster which is nice-to-have
- tsx noticed warned we were using module.exports in a esm file which looks like a mistake so I fixed that
An example is if these scripts wanted to use viem/wagmi in future they would break without updating the package to esm
=> Switch ts-node to tsx

src/schemas.ts, src/types.ts
As more chains get added to the tokenlist our previous schema requirements become too much of a burden to maintain. This change only requires that at least one of the required chains is specified in the token schema.
Fixes #[FE-1360](https://linear.app/optimism/issue/FE-1360)
=> FE-1360: simplify tokens schema

data/frxETH/data.json
No l2Bridge method is defined.
https://community.optimism.io/docs/developers/bridge/standard-bridge/#depositing-erc20s
=> Add nobridge to frxETH

src/chains.ts, src/types.ts, src/validate.ts
Fixes #[FE-1380](https://linear.app/optimism/issue/FE-1380/validate-base-goerli-using-standard-l2-factory)
=> FE-1380: validate all standard l2 tokens using StandardL2TokenCreated event

.github/workflows/generate.yml, package.json
To get this working, I changed the checkout step to not use the PAT token. The action now defaults to using the GITHUB_TOKEN token. Here is a [link](https://github.com/ethereum-optimism/ethereum-optimism.github.io/actions/runs/4633522133) to a successful run of the job after making this change.
=> FE-1365: Fix generate workflow

src/generate.ts, tests/__snapshots__/generate.test.ts.snap
This is a unique, required field that will be utilized by the Optimism Bridge UI in order to join tokens across chains.
=> FE-1425: Add opTokenId field to tokenlist

data/COLLAB/data.json
No l2Bridge method is defined.
https://community.optimism.io/docs/developers/bridge/standard-bridge/#depositing-erc20s
=> Add nobridge to COLLAB

data/COLLAB/data.json
Collab token was updated to include l2bridge method. Removing no bridge flag
=> Remove nobridge from COLLAb

README.md, data/BitBTC/data.json, data/DAI/data.json, data/ECO/data.json, data/SNX/data.json, data/USX/data.json, data/sUSD/data.json, data/wstETH/data.json, optimism.tokenlist.json, package.json, src/chains.ts, src/generate.ts, src/types.ts, src/validate.ts, tests/__snapshots__/generate.test.ts.snap
This will unblock people from adding base tokens to the tokenlist and will not be a breaking change to any consumers that are currently using the `optimismBridgeAddress` extension for optimism assets.
This has potential to be a breaking change for consumers that are using this token to bridge base assets. If using this for base assets, the `baseBridgeAddress` extension should be used instead of the `optimismBridgeAddress` for tokens that are being bridged on base.
Long term, we should specify bridges by creating a mapping from chain id to bridge address.
=> FE-1512: Add baseBridgeAddress extension for specifying base specific bridges

.github/workflows/label-base-token.yml
Uses OptimismBot token to create PR label, since it requires enhanced permissions compared to other actions.
=> use OptimismBot token to create label

data/RSR/data.json
Revert the base-goerli section from RSR config
=> remove base-goerli config from RSR

data/APT/data.json, data/SOL/data.json
These base related token listings were not routed through CB for approval and will have to be resubmitted.
cc @aadam-10 & apologies for the confusion
=> remove SOL/APT base-goerli token listings

.github/CODEOWNERS
Updating codeowners to reflect new reviewers, which will be @ethereum-optimism/devxpod 
Co-ownership / response this week, fully swapping to devX reviewers next week
=> Updating codeowners to DevX

data/WETH/data.json
For WETH we have optimism and base-goerli but not ethereum, optimism-goerli and (now) base-mainnet. Adding those in for consistency.
=> add WETH for ethereum, base-mainnet, and optimism-goerli networks

.github/CODEOWNERS
Currently Ecopod doesn't have the permissions to approve and merge tokenlist PRs, which may become blocking. 
The intention is not for Ecopod to keep being the owner, but rather unblock the Ecopod from merging tokenlist PRs. I also want to make sure this doesn't mean ecopod NEEDS to approve a PR for it to be merged.
=> Add Ecopod back to CODEOWNERS

src/chains.ts
The Chain ID has a typo on some assets and also in `src/chains.ts`; this fixes it to be 8453 instead of 8543. This also updates the mainnet RPC now that it is live.
**Tests**
**Metadata**
=> tokenlist: Fix Chain ID for Base

README.md
Right now the Base and Optimism token factories generate identical token address sequences leading to address conflicts across the two chains.   This PR adds instructions for anyone adding a Base token to use an alternate factory contract while we sort this out.
**Tests**
**Metadata**
=> Update Base token instructions to use alternate token factory

data/FRAX/data.json, data/FXS/data.json, data/frxETH/data.json
Frax tokens follow a custom bridge implementation. nobridge should be set to true for the following PRs merged in
#472,
#473,
#474
=> mark frax tokens as nobridge:true

data/NOGS/data.json
Following up from https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/458, this PR adds mapping for NOGS on mainnet.
=> Add NOGS on mainnet

README.md
fixes link to Base token factory info which was previously broken
=> fix link to alternate token factory

src/chains.ts
- Sepolia is broke because it's not on infura provider in ethers v5
=> fix: Sepolia build

data/POOL/data.json
@roberto-bayardo 
Hello, PoolTogether plans to deploy the new Version to Base in the future, so I wanna make sure the bridged token is working and users can bridge it through the official Base Bridge UI.
Token deployed through the OptimismMintableERC20Factory [0xf23d369d7471bd9f6487e198723eea023389f1d4](https://basescan.org/address/0xf23d369d7471bd9f6487e198723eea023389f1d4) according to ReadMe and Docs.
=> Add POOL Base contract

.github/mergify.yml
- remove automatic updates as it makes maintence of tokenlist significantly more difficult
- Because tokens are added independently this is unlikely to cause issues of 2 tokens conflicting with each other. It's unlikely someone updates the same token in 2 open prs
=> chore: Remove automatic updates

data/BridgedUSDC/data.json
PR https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/537/files introduced a new token `BridgedUSDC`, however in order for this token to be bridgeable it needs to contain both l1 and l2 tokens. This PR adds the L1 USDC tokens to `BridgedUSDC`
=> Add l1 USDC tokens to `BridgedUSDC`

.github/CODEOWNERS
Removing ecopod from CODEOWNERS as devx team has been DRI for tokenlist PRs.
=> Remove ecopod from codeowners

data/ARPA/data.json
Adding BASE mainnet mintable ERC20 contract address of ARPA
BASE:
https://basescan.org/address/0x1c9fa01e87487712706fb469a13beb234262c867
Ethereum:
https://etherscan.io/token/0xBA50933C268F567BDC86E1aC131BE072C6B0b71a
=> adding mintable base erc20 contract address of ARPA

data/weETH/data.json
This is a resubmit of this pr that accidentally got merged without approval: https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/589
add ether.fi weETH for Base mainnet
mainnet: https://basescan.org/address/0x4c94DE27c94962Dba6Ebb77924Ac54189db75EFA#code
=> add ether.fi weETH for Base mainnet

.github/workflows/stale.yml
Stale time is too aggressive ever since we started requring both base and OP approval
=> fix: Increase stale time

data/SNT/data.json
Following https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/559, this adds SNT for Sepolia and OP Sepolia to the token bridge UI.
=> Add Sepolia SNT and OP Sepolia SNT

data/BTRST/data.json
Adds addresses for Sepolia, Goerli, Base-Sepolia, and Base-Goerli for the BTRST token
**Tests**
No new tests.
=> Add BTRST Sepolia and Goerli and Base addresses

data/OLAS/data.json, data/OLAS/logo.svg
Add OLAS token to the Optimism network.
Token Ethereum mainnet address: https://etherscan.io/address/0x0001A500A6B18995B03f44bb040A5fFc28E45CB0
Token Optimism mainnet address: https://optimistic.etherscan.io/address/0xFC2E6e6BCbd49ccf3A5f029c79984372DcBFE527
**Tests**
Tests are not provided as the contract has been deployed by the [OptimismMintableERC20Factory](https://optimistic.etherscan.io/address/0x4200000000000000000000000000000000000012).
No additional context.
**Metadata**
N/A
=> chore: adding OLAS token to Optimism

data/USDT/data.json, src/chains.ts
This is the main USDT token on Mode network to be used with the StandardBridge and is paired with the USDT token `0xdac17f958d2ee523a2206206994597c13d831ec7` on Ethereum mainnet.
USDT token address on Mode is `0xf0F161fDA2712DB8b566946122a5af183995e2eD` and is referenced in Mode's main docs https://docs.mode.network/mode-developer-mainnet/mainnet-contract-addresses#token-addresses
This token is deployed using OptimismMintableERC20 directly without using the factory because the factory only supports 18 decimals while USDT requires 6 decimals.
=> Add USDT token address in Mode chain

src/types.ts
It looks like this [PR](https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/579), which added the mode chain, never added mode to the `l2Chains` array which caused many of the CI checks and actions for this repo to break
=> Add mode to l2Chains array

data/FOAM/data.json
Adds the [FOAM token](https://www.coingecko.com/en/coins/foam) to the Superchain list with Mainnet and Base addresses
ETH Mainnet address: https://etherscan.io/address/0x4946fcea7c692606e8908002e55a582af44ac121
Base address: https://basescan.org/address/0x6059d0ed9368c36941514d2864fD114a84853d5a
**Tests**
N/A, deployed to Base using the Base OptimismMintableERC20Factory at `0xf23d369d7471bd9f6487e198723eea023389f1d4`
Factory transaction: https://basescan.org/tx/0x14121db9ec5d3ff1327e0367f4352e66d45fb74ac4a4cecf418b670a8b0d359e
=> add FOAM to Base

data/PEPE/data.json
Add Pepe address for Base network.
**Tests**
This is updating a token info json with a new address for base network so test is not added.
L2 Standard token creation tx:
https://basescan.org/tx/0xb6435cbf60cd4d82303d7774a9b9cea97a8cb543f1052fc4bd72ea08622b4331#eventlog
L1 token address:
0x6982508145454Ce325dDbE47a25d4ec3d2311933
=> feat: add bridged PEPE on base

data/RAZOR/data.json
- Linked to an update requested on a previous PR which was merged. But the token still does not reflect on the OP bridge UI. 
- https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/736
=> chore: update the name of RAZOR token to match contract

data/CHAR/data.json, data/CHAR/logo.svg
adding Toucan's CHAR token on Base
@cfluke-cb @wbnns for your review, thanks!
=> add CHAR on Base

package.json, pnpm-lock.yaml, src/schemas.ts
Our local schema is checked as well as checked against the uniswap tokenlist schema.
Latest version of the uniswap token schema supports unicode characters
=> fix: unicode support

data/LIKE/data.json
The maintainers changed the folder name from “❤️” to “LIKE” because the emoji as a folder name was problematic for the repo, but when the folder name was change the admins also changed the token symbol, this PR edits the token symbol back to “❤️” consistent with both the Ethereum Mainnet and Base contracts.
[@wbnns](https://github.com/wbnns) [@hamdiallam](https://github.com/hamdiallam)
**Tests**
**Metadata**
=> Update LIKE data.json (update token symbol to match contract)

README.md
We are following the STL and see each new PR for Base; it is not necessary to tag maintainers for Base tokens going forward
**Tests**
N/A
N/A
**Metadata**
N/A
=> docs(README): Drop req to tag Base maintainer

data/SNX/data.json
SNX has a canonical implementation on Base and Mode. Per request from Kaleb we are removing the noBridge flag. 
This means users will stay face gas issues when trying to bridge to OPM but the SNX token will show up with the correct syntax going forward. 
See issue 857 in EcoPod repo for more info
=> Remove noBridge from SNX

data/MKR/data.json
Reverts ethereum-optimism/ethereum-optimism.github.io#807 as the provided address is invalid.
=> Revert "Add base L2 token address for MKR"

data/KROM/data.json
$KROM token is added on Base. The contract address is: 0xdfF3C626De2Ccd1ECf67E97abc8A74C102C86545
=> add-krom-to-base

data/MUGLOO/data.json
A cross chain token for my upcoming project for OpStack.
- Already listed for Optimism.
L1 Contract:
Ethereum: [0x8e3c68a9c10d3bf2aaf14f2e569a8223f21bf2b6](https://etherscan.io/address/0x8e3c68a9c10d3bf2aaf14f2e569a8223f21bf2b6)
- L2's 
Base:[0xE009e453Ac69B0E9602BA091D5331B31B03D3039](https://base.blockscout.com/address/0xE009e453Ac69B0E9602BA091D5331B31B03D3039)
Metall2:~[0xf1F9Ccc7638F124c3d9354Be0edE2ACb5F0A15Bc](https://explorer.metall2.com/address/0xf1F9Ccc7638F124c3d9354Be0edE2ACb5F0A15Bc)~
going with Base for now as per below thread, will raise a new one for Metall2
=> feat-add-mugloo-base-metall2

data/MUGLOO/data.json
This reverts commit 69b96899b837dfb3ed40a081eca0781af08d432b -- the source code for the deploy smart contract isn't verified; in addition, it's using custom decimals. We should confirm that it's using a contract that bridges won't have issues with, in addition to ensuring the source code is verified.
Contract: https://basescan.org/address/0xE009e453Ac69B0E9602BA091D5331B31B03D3039#code
=> Revert "feat-add-mugloo-base-metall2 (#921)"

data/USDT/data.json
Add USDT contract address for Lisk and Lisk sepolia
**Tests**
We run the tests indicated in the README:
```npx tsx ./bin/cli.ts validate --datadir ./data --tokens USDT```
=> Feat: add USDT token address for Lisk mainnet and testnet

data/USDT/data.json
Remove the USDT address for Lisk Sepolia testnet added by mistake by this PR: https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/926 (sorry about that 😓 )
**Tests**
We ran the tests indicated in the README:
```npx tsx ./bin/cli.ts validate --datadir ./data --tokens USDT```
=> Remove USDT address for Lisk sepolia

data/WBTC/data.json
Add address for WBTC on Lisk L2.
**Tests**
We ran the WBTC test with:
```npx tsx ./bin/cli.ts validate --datadir ./data --tokens WBTC```
=> Add WBTC token to Lisk

data/SNT/data.json
- use checksum address for SNT on Ethereum
- https://eips.ethereum.org/EIPS/eip-55
- when comparing to another token list like https://ipfs.io/ipns/tokens.uniswap.org, SNT on Ethereum would come up as unique but essentially same due to difference in casing
- https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/559
- https://etherscan.io/address/0x744d70fdbe2ba4cf95131626614a1763df805b9e returns `0x744d70FDBE2Ba4CF95131626614a1763DF805B9E`
=> Use checksum address for SNT on Ethereum

data/BridgedUSDC/data.json
Bridged USDC is deployed on Lisk using [Bridged USDC Standard for the OP Stack](https://github.com/defi-wonderland/opUSDC) which also deploys and uses new L1 and L2 bridges. 
- Added Bridged USDC deployment address, name and synbol on Lisk
- Added L1 bridge address for Lisk on Ethereum 
- Added L2 bridge address on Lisk
**Tests**
Ran validation test indicated in the `README`:
`npx tsx ./bin/cli.ts validate --datadir ./data --tokens USDC`
=> Add Bridged USDC to Lisk

data/AAVE/data.json
Implement the AAVE token on Base.
AAVE token has been deployed on Base on this tx: https://basescan.org/tx/0x1c29e61ba6da00244e6b7f6bb8153b1c8c0de762d562ba65f8369bfb1e9e68b7
- localToken: [0x63706e401c06ac8513145b7687A14804d17f814b](https://basescan.org/address/0x63706e401c06ac8513145b7687A14804d17f814b)  
- remoteToken: [0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9](https://etherscan.io/address/0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9)
**Tests**
**Metadata**
=> ✨ add AAVE token on base

data/wstETH/data.json
wstETH is deployed on Lisk following rollup bridging [guide by Lido](https://docs.lido.fi/token-guides/wsteth-bridging-guide/#why-is-this-guide-needed) which also deploys and uses custom dedicated L1 and L2 bridges. 
- Added wstETH deployment addresses for Lisk and Lisk Sepolia
- Added L1 bridge addresses for Lisk and Lisk Sepolia
- Added L2 bridge addresses for Lisk and Lisk Sepolia
**Tests**
Ran validation test indicated in the `README`:
`npx tsx ./bin/cli.ts validate --datadir ./data --tokens wstETH`
=> Add wstETH to Lisk and Lisk Sepolia

.circleci/config.yml
This pull request includes updates to the `.circleci/config.yml` file to streamline the CI/CD pipeline by removing an unnecessary step and adding steps to configure and verify the NPM token.
CI/CD pipeline improvements:
* [`.circleci/config.yml`](diffhunk://#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47L45): Removed the `continue-if-not-bot` step to simplify the pipeline.
* [`.circleci/config.yml`](diffhunk://#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47L90-R95): Added steps to configure the NPM token and verify it before publishing the package.
**Tests**
**Metadata**
=> fix publishing of tokenlist and removing the requirement for not bot push

.circleci/config.yml, .npmrc
This pull request includes several changes to the `.circleci/config.yml` and `.npmrc` files to improve the CI/CD pipeline and token handling. The most important changes include adding a step to continue if not a bot, removing unnecessary NPM token configuration, and modifying the `.npmrc` file to use a different token syntax.
Improvements to CI/CD pipeline:
* [`.circleci/config.yml`](diffhunk://#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R45): Added a step to continue the process if the user is not a bot.
* [`.circleci/config.yml`](diffhunk://#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47L89-L100): Removed the unnecessary NPM token configuration step to streamline the pipeline.
Token handling:
* …
=> Re enable bot restriction and add .nojekyll for github pages

data/SMT/data.json
Add SMT token support to the Mode and Lisk networks.
**Tests**
No tests. Used standard token bridge.
**Metadata**
=> add: new SMT addresses for Mode and Lisk networks

data/WBTC/data.json
We wrongly deployed the Celo L2 WBTC token with 16 instead of 8 decimals.
This PR updates to a correct token with 8 decimals.
The old token was only used by me for testing: https://celoscan.io/address/0xE79a3d9f18C20c93DbEc8db8B28C6542d63df5E9
=> celo: Use WBTC with correct decimals

src/chains.ts, src/types.ts
This PR adds Swellchain, Ink, and Worldchain to the list of Superchain chains supported in the tokenlist.
=> Add swellchain, ink, and worldchain to chains

.circleci/config.yml, data/USD₮0/data.json, src/chains.ts, src/generate.ts, src/schemas.ts
Closes https://github.com/ethereum-optimism/ethereum-optimism.github.io/issues/1141
This PR contains a few changes to get validation working again:
- Encode the token symbol part of the `logoURI` in order to avoid failures when token symbols contain characters that do not pass uri validation: ([example](https://circleci-tasks-prod.s3.us-east-1.amazonaws.com/forks/storage/artifacts/333b3b63-b6a9-4616-b483-d8a655eafa6c/934993580/782a4c86-a600-4555-b7ba-9c636a2804c4/0/validation_results.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Checksum-Mode=ENABLED&X-Amz-Credential=ASIAQVFQINEON5Y2P3QV%2F20250513%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250513T203015Z&X-Amz-Expires=60&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEE0aCXVzLWVhc3QtMSJIMEYCIQCFJXne60CXIzjMC2LZ%2BrkDA6fu6uWvuoxe8tUzaUQ%2BawIhALIN4HT …
=> fix: handle special characters in token filenames

.circleci/config.yml, optimism.tokenlist.json
Versions after 10.0.238 of `@eth-optimism/tokenlist` do not include a `dist` directory, resulting in the following error when attempting to import the package:
```
Module not found: Can't resolve '@eth-optimism/tokenlist'
```
The CircleCI publish workflow was missing a critical build step. While the workflow correctly:
1. Generated the token list (`pnpm generate:ci`)
2. Bumped the version and committed changes
3. Published the package (`pnpm publish`)
It was **not** building the `dist` directory that contains the compiled JavaScript and TypeScript declaration files that consumers need to import the package.
The `package.json` correctly specifies:
- `"main": "dist/index.js"`
- `"module": "dist/index.mjs"` 
- `"types": "dist/index.d.ts"`
- `"files": ["dist"]`
But without the build step, the …
=> Fix missing dist directory in published npm package

data/bwAJNA/data.json
Replaced the broken website link with the main Ajna Finance URL in the data.json file.
This update ensures users can access the main site for more information about AJNA tokens and related services.
=> Update Website Link for AJNA

src/types.ts
Replace deprecated OptimismGoerli link with working OptimismSepolia link
=> fix: update Optimism testnet reference link

data/ARCV2/data.json
Removed nobridge to ensure the arcv2 token addresses and bridges are discoverable.
=> remove nobridge to make arcv2 discoverable
