ethereum-optimism/ethereum-optimism.github.io

optimism.tokenlist.json

reference: https://raw.githubusercontent.com/Synthetixio/synthetix/develop/publish/deployed/mainnet-ovm/deployment.json

Fixes sUSD chain ID

---

src/validate.ts

Add default infura key to be used by forks

Make CI work for forks

---

.github/CODEOWNERS

We need clear ownership of each repo/product. Since I've been doing most of the work on the token list I'm nominating myself as the codeowner.

Add Elena as codeowner for token list repo

---

optimism.tokenlist.json

Updated the DCN info with mainnet data

---

optimism.tokenlist.json

Description :
- Added PERP L1 and L2 token details to tokens list

Add PERP to optimism

---

optimism.tokenlist.json

Description
Add [DF](https://etherscan.io/address/0x431ad2ff6a9c365805ebad47ee021148d6f7dbe0) and [USX](https://etherscan.io/address/0x0a5e677a6a24b2f1a2bf4f3bffc443231d2fdec8) on the Optimism Token List

Add DF, USX token

---

optimism.tokenlist.json

Updated the Synthetix bridge addresses in the `Diphda` release: https://github.com/Synthetixio/synthetix/releases/tag/v2.64.1

Updated Synthetix bridge addresses

---

package-lock.json
yarn.lock

Fixing outdated package-lock & yarn.lock

updated package-lock & yarn.lock

---

optimism.tokenlist.json

When adding tokens we need to increment the minor version. This was not done for the OP token so doing it here now

incrementing minor version

---

optimism.tokenlist.json

OP token fix

---

src/validate.ts
yarn.lock

This fixes the CI failing in downstream PRs.

Updated exclusion list with theDAO

---

optimism.tokenlist.json

Added the SNX token deployments for the `Goerli` and `Optimistic Goerli` networks.

Add Goerli SNX to tokenlist

---

src/generate.js

Generate token list with the fix has correct logo extensions:
```
{
"name": "Optimism",
"logoURI": "https://ethereum-optimism.github.io/optimism.svg",
"keywords": [
"scaling",
"layer2",
"infrastructure"
],
"timestamp": "2022-08-17T23:55:06.143Z",
"tokens": [
{
"chainId": 1,
"address": "0xb6ed7644c69416d67b522e20bc294a9a9b405b31",
"name": "0xBitcoin",
"symbol": "0xBTC",
"decimals": 8,
"logoURI": "https://ethereum-optimism.github.io/data/0xBTC/logo.png",
"extensions": {
"optimismBridgeAddress": "0x99C9fc46f92E8a1c0deC1b1747d010903E884bE1"
}
},
{
"chainId": 10,
"address": "0xe0BB0D3DE8c10976511e5030cA403dBf4c25165B",
"name": "0xBitcoin",
"symbol": "0xBTC",
"decimals": 8,
"logoURI": "https://ethereum-optimism.github.io/data/0xBTC/logo.png",
"extensions": {
"optimismBridgeAddress": …
```

fix - add the correct logo extension when generating the list

---

data/DAI/data.json

Add Goerli addresses to DAI 
L1
- token https://goerli.etherscan.io/address/0x11fe4b6ae13d2a6055c8d9cf65c55bac32b5d844
- bridge https://goerli.etherscan.io/address/0x05a388db09c2d44ec0b00ee188cd42365c42df23#code
L2 
- token https://blockscout.com/optimism/goerli/address/0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1/contracts#address-tabs
- bridge https://blockscout.com/optimism/goerli/address/0x467194771dAe2967Aef3ECbEDD3Bf9a310C76C65/contracts#address-tabs
**Metadata**
- Fixes https://linear.app/optimism/issue/ENG-2573/add-migrated-tokens-to-tokenlist

Add Goerli DAI

---

data/sUSD/data.json

Add Optimism Goerli address for sUSD https://blockscout.com/optimism/goerli/address/0xeBaEAAD9236615542844adC5c149F86C36aD1136
**Metadata**
- Fixes https://linear.app/optimism/issue/ENG-2573/add-migrated-tokens-to-tokenlist

Add Optimism Goerli sUSD

---

data/LINK/data.json

Add Goerli addresses for LINK
- L1 https://goerli.etherscan.io/address/0x326c977e6efc84e512bb9c30f76e30c160ed06fb
- L2 https://blockscout.com/optimism/goerli/address/0xdc2CC710e42857672E7907CF474a69B63B93089f/contracts#address-tabs
**Metadata**
- Fixes https://linear.app/optimism/issue/ENG-2573/add-migrated-tokens-to-tokenlist

Add Goerli LINK

---

.github/workflows/generate.yml
.github/workflows/validate.yml

Only runs generate.yml when we're on the primary repo, not on forks.

fix(ci): only generate list on primary repo

---

.github/workflows/validate.yml
.gitignore
scripts/generate.js
scripts/validate.js
src/errors.js
src/generate.js

Adds better error comments when CI validation fails. CI comment will now
include the exact error message that caused validation to fail.

feat(ci): better error comments

---

.github/workflows/generate.yml
.github/workflows/validate.yml
scripts/validate.js
src/generate.js

Limits validation to only changed files, speeding up CI time and setting
us up for a few upcoming PRs.

 feat(ci): only check changed files 

---

.github/workflows/validate.yml
package.json
src/generate.js
yarn.lock

Requires manual review for unverified contracts.

feat(ci): require review for unverified contracts

---

.github/workflows/validate.yml
src/generate.js

Tweaks CI to give more detail in comments when manual review is
required.

fix(ci): better comments for manual review

---

.github/workflows/validate.yml
src/errors.js
src/generate.js
src/schemas.js
tests/data/ETH/data.json
tests/data/OP/data.json

Adds all remaining required checks to CI and triggers manual review in a
few more places.

feat(ci): add all required checks to CI

---

data/OUTb/data.json
data/OUTb/logo.svg

This is a testing token which needs to be bridgeable between Goerli and Optimism Goerli.

OUTb token

---

.github/mergify.yml

Mergify will automatically merge PRs when they receive one approval.

feat(ci): add mergify config

---

.github/workflows/generate.yml
.github/workflows/test.yml
.github/workflows/validate.yml

Fixes workflow names in yml files. Allows us to make sure that workflows
are running to completion before anything gets merged.

fix(ci): use correct workflow names

---

.github/workflows/validate.yml

Fixes another bug in validation CI.

fix(ci): correct cli usage in validate

---

bin/cli.js
src/validate.js

Splits the token list, otherwise we get bugs where unrelated tokens
trigger in validation.

fix(ci): split token list

---

.github/workflows/generate.yml

Gives the generation step a personal access token

fix(ci): give generate a PAT

---

.github/workflows/generate.yml

Prevents an infinite loop in CI that was newly triggered as a result
of adding the Personal Access Token functionality.

fix(ci): prevent infinite loop

---

.github/workflows/validate.yml

Disables the Validation workflow

fix(ci): disable validation

---

optimism.tokenlist.json

Currently the token list generation is turned off.
- generate manually `yarn generate --datadir ./data --outfile optimism.tokenlist.json`

Generate token list

---

.github/workflows/validate.yml

Reactivates the validation CI step in a safe way.

fix(ci): reactivate validation script

---

.github/workflows/validate.yml

CI was not properly detecting changed files after we changed to pull_request instead of pull_request_target.

fix(ci): properly detect changed files

---

.github/workflows/validate.yml

Print errors during validation step.

fix(ci): print validation errors

---

.github/workflows/validate.yml

Fix Print output

---

.github/mergify.yml

This makes it so all prs autoupdate

Allow mergify to auto update

---

.github/mergify.yml

Enable mergify and say hi

---

.github/workflows/generate.yml

Automatically patch the version in package.json whenever a new token list publishes

feat: Patch version of token list when published

---

data/veKWENTA/data.json
data/veKWENTA/logo.svg

Add $veKWENTA erc20 token to the Optimism Token List
* Create a folder for token
* Add a logo
* Add defining data for the token
$veKWENTA is acquired by users on mainnet but the token's utility exists on Optimism (please refer to README: https://github.com/Kwenta/veKWENTA/blob/main/README.md)

💥 Add veKWENTA

---

data/ETH/data.json

add goerli eth

---

README.md

Make a change to try to trigger generate

Test Generate

---

.github/workflows/generate.yml

Allows us to manually trigger this action

Add workflow_dispatch to generate action

---

optimism.tokenlist.json

automatic version of doing this is wrecked

manuallly generate a new list

---

.github/workflows/generate.yml

Switch order of patch and commit

Switch order of patch and commit

---

data/FRAX/data.json

No custom bridge defined for non-factory token, setting as no-bridge.

Add noBridge to frax

---

data/stkLYRA/data.json
data/stkLYRA/logo.svg

Adding the Staked LYRA token.
**Tests**
n/a
**Invariants**
n/a
n/a
**Metadata**
n/a

Add stkLYRA

---

data/MOCHI/data.json

Adding MOCHI tokens addresses for Mainnet and Optimism (replacing #269 due to validation issues)
**Tests**
I don't think I need tests for this sort of update
**Invariants**
No invariants here
Can't wait to...
```py
^^
^^      ..                                       ..
[]                                       []
.:[]:_          ^^                       ,:[]:.
.: :[]: :-.                             ,-: :[]: :.
.: : :[]: : :`._                       ,.': : :[]: : :.
.: : : :[]: : : : :-._               _,-: : : : :[]: : : :.
_..: : : : :[]: : : : : : :-._________.-: : : : : : :[]: : : : :-._
_:_:_:_:_:_:[]:_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:[]:_:_:_:_:_:_
!!!!!!!!!!!![]!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!![]!!!!!!!!!!!!! …
```

MOCHI main and OP

---

optimism.tokenomics.json

Add a timestamp to the json file

Add a timestamp

---

data/JRT/data.json
data/JRT/logo.svg
optimism.tokenlist.json

**Tests**
**Invariants**
For changes to critical code paths, please list and describe the invariants or key security properties of your new or changed code.
**Metadata**

Add JRT token to data and tokenlist

---

optimism.tokenomics.json

update circulating supply

---

README.md

As requested in https://oplabs-pbc.slack.com/archives/C0229H2N4MD/p1677793120544359

feat(README.md): Add warning (unsupported confs)

---

data/VITA/data.json
data/VITA/logo.svg

Add the VitaDAO governance token
- https://www.coingecko.com/en/coins/vitadao

Add VITA token

---

optimism.tokenlist.json

generate list

---

data/alETH/data.json

No l2Bridge method is defined.

Add no bridge to alETH

---

src/validate.ts

The etherscan validation logic is currently broken because it expects a `qResult` field in the response. According to the [etherscan api docs](https://docs.etherscan.io/api-endpoints/contracts#get-contract-source-code-for-verified-contract-source-codes) the response returns a `result` field. This PR switches the validation to use the `result` field.
Fixes #[FE-1371](https://linear.app/optimism/issue/FE-1371)

FE-1371: fix etherscan validation logic

---

data/MTA/data.json
data/MTA/logo.svg

This PR adds the MTA token. We plan to launch mStable products and build MTA liquidity on Optimism.

Add MTA token

---

README.md

Adding paragraph to communicate that you do not need to be added to list in order to bridge/deploy on Superchain

Add clarity to readme

---

src/defaultTokens.ts

Add CBETH to default

---

data/COMP/data.json

Add base-goerli address to COMP's data.json.

Add base-goerli address for COMP

---

data/MET/data.json
data/MET/logo.svg

Add Metronome(MET) token

---

README.md

The result of a discord thread where an app developer thought something is wrong.

feat(README.md): Add a note about timing of UI updates

---

data/ECO/data.json

Updated ECO bridge addresses for `ethereum`, `optimism`, `goerli`, and `optimism-goerli`.

New L2 ECO and bridge addresses

---

src/defaultTokens.ts

Adding WLD to default list on UI

---

data/USDC/data.json

Add `base-goerli` and `base` mainnet USDbC.
[base goerli basescan](https://goerli.basescan.org/address/0x853154e2A5604E5C74a2546E2871Ad44932eB92C#code)
[base mainnet basescan](https://basescan.org/address/0xd9aaec86b65d86f6a7b5b1b0c42ffa531710b6ca#readProxyContract)
cc @roberto-bayardo

USD Base Coin

---

data/SUSHI/data.json

+ Add SUSHI base address to existing entry
+ Tx for the token created to link with mainnet SUSHI token -> https://basescan.org/tx/0x5d05035db18c721040f76178c46f60c68d252ae660d4f11a4ebad43d858a518a

Add SUSHI to Base

---

data/USDC/data.json

Following announcement from Circle, updating Bridged USDC to reflect referenced symbol of USDC.e

Updating Bridged USDC reference symbol

---

src/chains.ts
src/types.ts

fix: Fix tokenlist build

---

data/PIP/data.json

added PIP to BASE

---

data/DAI/data.json

This is an upgraded token version of DAI for PGN which now includes permit functionality.
This replaces the first version of DAI which did not have permit functionality.
**Tests**
**Metadata**

New version of DAI with permit functionality has been deployed.

---

data/RDMP/data.json

@roberto-bayardo 
(https://github.com/roberto-bayardo)
Adding Redemption Finance (RDMP) to be listed
**Tests**
**Metadata**

Add Redemption Finance

---

tests/__snapshots__/generate.test.ts.snap

- Update snapshots that broke from a major bump

fix: Update snapshot

---

data/weETH/data.json
data/weETH/logo.svg

add Ether.fi weETH for goerli + optimism-goerli
`goerli`: https://goerli.etherscan.io/address/0xAc687b5ccd042e0d70405219112d95035938e3e8
`optimism-goerli`: https://goerli-optimism.etherscan.io/address/0x7e7d4467112689329f7e06571ed0e8cbad4910ee

add Ether.fi weETH for goerli + optimism-goerli

---

data/weETH/data.json

add ether.fi weETH for Base mainnet
`mainnet`: https://basescan.org/address/0x4c94DE27c94962Dba6Ebb77924Ac54189db75EFA#code

add ether.fi weETH for Base mainnet

---

data/GROW/data.json

Add GROW token on Base. 
This token is mainnet native and already added to Optimism. 
Adding @roberto-bayardo from Base

Add GROW on Base

---

data/KOMPETE/data.json

Add KOMPETE token to Base. We are live on mainnet, and have created the token on Base using the Mintable Factory. 
@roberto-bayardo

Add KOMPETE to Base Chain

---

data/MET/data.json

Add MET on BASE
Adding Metronome on BASE & Bridge Support - per Jesse cc: @green-jeff @roberto-bayardo

Add MET to BASE

---

data/TKN/data.json

Adding the TKN Base token address to join the existing ETH Mainnet and OP Mainnet addresses

Modified TKN to add bridged Base token address

---

data/IPT/data.json
data/IPT/logo.svg

* mkdir data/IPT and update data/IPT/data.json
* update data/IPT/logo.svg
Co-authored-by: Jake Barber <jbarber@gfxlabs.io>
[IPT ](https://etherscan.io/address/0xd909C5862Cdb164aDB949D92622082f0092eFC3d) is the governance token for [Interest Protocol](https://interestprotocol.io/).
[0x4ea5eC30487132328616dBa55E46346CA840B685](https://optimistic.etherscan.io/address/0x4ea5eC30487132328616dBa55E46346CA840B685#code) is the OptimismMintableERC20 bridged to Optimism.

    IPT token added

---

data/wstETH/data.json

Add Sepoliaa and Optimism-Sepolia testnet configs for wstETH token.
**Tests**
According to the instruction, tests are not required.

Add config for wstETH token on Sepolia and Optimism-Sepolia

---

data/SNX/data.json

Closes https://github.com/ethereum-optimism/ecopod/issues/857

Add nobridge:true to SNX token

---

README.md

Adding guidelines for Zora and Mode tokenlist reviews.

[Update] Add multichain process to README

---

data/BITCOIN/data.json

HarryPotterObamaSonic10Inu (Ticker: BITCOIN) is a endgame of crypto-assets (0 Tax). BITCOIN incentivizes the creation of novel and entertaining meme content. With ownership renounced and Liquidity locked, our robust growing community has taken the lead; we have successfully completed a full audit, an NFT collection, and are exploring partnerships with other tokens in the space, a one-of-a -kind website, and one-of-a-kind merchandise and ecommerce site in the works based on the legendary meme that inspired BITCOIN's creation. Our goal is to create an ecosystem for active community members to meet, collaborate, and share our rich lore (the archive of our token's storied history) with the world.
Ethereum CA: 0x72e4f9F808C49A2a61dE9C5896298920Dc4EEEa9

$BITCOIN on Base

---

data/EVERY/data.json
data/EVERY/logo.svg

Adding EVERY to Base Bridge, happy to provide any info necessary

Add EVERY to Base

---

data/DF/data.json

Deploy DF token on base network.

Add new network for DF.

---

data/IOTX/data.json
data/IOTX/logo.svg

Adding Token `IOTX` to Base.
Token: https://basescan.org/address/0xbcbaf311cec8a4eac0430193a528d9ff27ae38c1 was created using 
https://basescan.org/address/0xf23d369d7471bd9f6487e198723eea023389f1d4#writeContract#F1 
Thanks!

Add IOTX to Base

---

data/WALLET/data.json
data/WALLET/logo.svg

Added Ambire Wallet token address to the token list for the Base bridge.
@cfluke-cb @taycaldwell @wbnns
**Tests**
N/A
N/A
**Metadata**
N/A

Add Ambire Wallet to Base

---

data/HAIR/data.json

Add Hair (HAIR) token on Base.
Hair Token token on Coingecko:https://www.coingecko.com/en/coins/hairdao
[@cfluke-cb](https://github.com/cfluke-cb), [taycaldwell](https://github.com/taycaldwell)  [wbnns](https://github.com/wbnns)

Add HAIR token to Base

---

data/ETHIX/data.json

Hi,
This PR adds EthicHub token => ETHIX on base and remove sepolia, optimism-sepolia and base-sepolia.
Thank you very much.

Add EthiHub token (ETHIX) on base mainnet and remove sepolia testnets tokens.

---

data/CIG/data.json
data/CIG/logo.svg

Description
Add the Cigarette token https://www.coingecko.com/en/coins/cigarette for Base
Ethereum
https://etherscan.io/token/0xCB56b52316041A62B6b5D0583DcE4A8AE7a3C629
Base
https://basescan.org/address/0xf88cf71b891a89a1cb02ec17ce3ad80e5ae31e1b
tagging @cfluke-cb, @taycaldwell and @wbnns

Add CIG to Base

---

data/TYBENG/data.json

Add new token TYBENG from ETH Sepolia to BASE Sepolia network.

:art: [support] Add TYBENG for BASE Sepolia [testnet]

---

data/CNG/data.json
data/CNG/logo.svg

Adds CNG Token
Ethereum: https://etherscan.io/token/0x5C1d9aA868a30795F92fAe903eDc9eFF269044bf
Optimism: https://optimistic.etherscan.io/address/0x1D015bF7d8a6fb0fc30959F3e12355530086b2A5

Adds CNG token

---

data/sDAI/data.json

Add sDAI ERC20 on Mode.

---

data/MUGLOO/data.json

This is a follow up PR with ref. to thread on #921 
L1 Contract:
Ethereum: [0x8e3c68a9c10d3bf2aaf14f2e569a8223f21bf2b6](https://etherscan.io/address/0x8e3c68a9c10d3bf2aaf14f2e569a8223f21bf2b6)
L2 Base Deployments:
Basescan : [0xe009e453ac69b0e9602ba091d5331b31b03d3039](https://basescan.org/address/0xe009e453ac69b0e9602ba091d5331b31b03d3039#code)
BaseBlockscout: [0xe009e453ac69b0e9602ba091d5331b31b03d3039](https://base.blockscout.com/address/0xE009e453Ac69B0E9602BA091D5331B31B03D3039?tab=contract)

Add MUGLOO to Base 

---

data/VSP/data.json
data/VSP/logo.svg

Add VSP token for Ethereum and Base.

Add VSP token

---

data/bwAJNA/data.json

bwAJNA address on Base was accidentally removed in Goerli removal. This PR readd it.
**Tests**
**Metadata**

readd bwAJNA Base address

---

data/BRIGHT/data.json
data/BRIGHT/logo.svg

Add BRIGHT to Unified token list.

add BRIGHT token

---

data/SPC/data.json
data/VSP/data.json
data/VUSD/data.json

Add SPC, VSP and VUSD tokens on Optimism. These tokens have already been added on Base.

Add SPC, VSP and VUSD to Optimism

---

data/MORPHO/data.json

Add Morpho token mainnet et base metadata

---

data/F/data.json
data/F/logo.svg

- Added `F` Token on Base chain.
- Added Website and Twitter for `F` Token.

Add F token on Base

---

data/Silo/data.json

List Silo token to bridge it on Optimism
Base token is already added in https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/891

Add Silo on Optimism

---

data/MINDS/data.json
data/MINDS/logo.svg

Add the MINDS token

---

data/MASK/data.json

Add Mask Network (MASK) on Base
**Deployment**
- Check token on Ethereum: [0x69af81e73A73B40adF4f3d4223Cd9b1ECE623074](https://etherscan.io/address/0x69af81e73A73B40adF4f3d4223Cd9b1ECE623074)
- Check token on Base: [0xD0a4D1889BbE483273f29b4aCdfAA567A67F99E1](https://basescan.org/address/0xD0a4D1889BbE483273f29b4aCdfAA567A67F99E1)

Add MASK on Base

---

data/ZENT/data.json
data/ZENT/logo.svg

Adds ZENT (Zentry Token) to Base
Native L1 Token: https://etherscan.io/token/0xdBB7a34Bf10169d6d2D0d02A6cbb436cF4381BFa
Base Token: https://basescan.org/token/0xdf49c226ED9CF05Be0e38cdb86Df4E8A945158B1

Add ZENT token to Base

---

data/stZENT/data.json
data/stZENT/logo.svg

Adds stZENT (Staked Zentry) to Base
Native L1 Token: https://etherscan.io/token/0x996d67aa9b37df96428ad3608cb21352bf1fdb90
Base Token: https://basescan.org/token/0x58cDA7e1ef2de86586033989f7Fe5dB705F2a2F5

Add stZENT to Base

---

data/USDT/data.json

Adds Tether deployment on Base
**Tests**
N/A
N/A
**Metadata**
N/A

Add Tether deployment on Base

---

data/PERP/data.json

Add [$PERP](https://www.coingecko.com/en/coins/perpetual-protocol) Token to Base chain

Add PERP Token 

---

.github/workflows/validate.yml

* Migrates to v4 github upload action, v3 has been [deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)

Migrate to v4 upload action

---

README.md
bin/cli.ts

README.md
Non-bridgable - Non-bridgeable `fix typo`
bin/cli.ts
tokens - token `correction`

fix spelling errors

---

data/AAVE/data.json
data/CRV/data.json
data/UNI/data.json
data/WBTC/data.json
data/WETH/data.json

Add token for Celo's native bridge.

token: Add Celo native bridge tokens

---

data/CATTBUTT/data.json
data/CATTBUTT/logo.svg

Add CATTBUTT token

---

data/BRZ/data.json
data/BRZ/logo.svg

Add BRZ Token

---

data/BTREE/data.json

add sepolia and base-sepolia addresses for BTREE token
**Tests**
**Metadata**

update: add sepolia and base-sepolia addresses for BTREE token

---

data/ICNT/data.json

Add ethereum and base addresses for ICNT token
**Tests**
**Metadata**

update: add ethereum and base addresses for ICNT token

---

data/1INCH/data.json
data/ACX/data.json
data/DAI/data.json
data/DOLA/data.json
data/GTC/data.json
data/LDO/data.json
data/LINK/data.json
data/LUSD/data.json
data/MKR/data.json
data/POOL/data.json
data/RPL/data.json
data/UMA/data.json
data/WLD/data.json
data/crvUSD/data.json
data/rETH/data.json
data/sDAI/data.json

This adds addresses on the Celo blockchain for multiple of the existing tokens. No other changes are intended.
Some missing trailing newlines have been added where they were missing.

Add more tokens for Celo blockchain

---

data/ENS/data.json

Adds the ENS token for Celo Mainnet.

celo: Add ENS token

---

src/validate.ts

CI validation has been experiencing intermittent failures when calling contract functions (decimals, symbol, name), even for valid deployed contracts. This affects legitimate token submissions and creates a poor contributor experience.
- Add `retryContractCall` helper function with exponential backoff
- Apply retry logic to all contract validation calls
- Use 3 retries with 1s, 2s, 4s delays between attempts
- Maintain validation integrity while improving CI reliability
- Resolves intermittent provider/network issues in CI environment
- Improves reliability for all token submissions
- No changes to validation logic - only adds resilience
- Better debugging with retry attempt logging
- ✅ Tested locally with problematic contracts
- ✅ Maintains all existing validation behavior
- ✅ Only …

fix: Add retry logic for contract validation calls

---

data/EL/data.json
data/EL/logo.svg

Added EL token to soneium
**Tests**
**Metadata**

feat: add EL to soneium

---

data/iRWA/data.json
data/iRWA/logo.svg

**About $iRWA**
$iRWA is the utility and governance token of the IncomRWA ecosystem.
It’s designed to reward active users, drive platform growth, and enable decentralized governance, all while aligning incentives around real-world asset (RWA) finance.

Add IncomRWA(iRWA) Token to Base Network
